import type { Metadata } from 'next'
import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <head>
        <meta
          name="description"
          content="Projeto de TCC apresentado para o curso Sistemas de Infornmação pela faculdade ENIAC"
        />
        <title>Petguardian</title>
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
